name: roadwise
description: "RoadWise - A gamified, Duolingo-style mobile app for learning road signs and traffic rules."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  confetti: ^0.8.0

  # State Management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0  # Updated from ^8.1.0 to ^9.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Navigation
  go_router: ^15.2.0

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.1.2

  # Database
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  path_provider: ^2.1.4

  # Network & API
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # Local Storage & Preferences
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Authentication & Security
  crypto: ^3.0.5

  # In-App Purchases
  in_app_purchase: ^3.2.0

  # Animations & UI Effects
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0

  # Image & Media
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.4.0

  # Permissions
  permission_handler: ^12.0.0+1

  # Local Notifications
  flutter_local_notifications: ^19.2.1

  # Audio
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.1.2
  isar_generator: ^3.0.0
  mocktail: ^1.0.0
  analyzer: ^5.13.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
